---
- name: Add ingress-nginx repo
  kubernetes.core.helm_repository:
    name: "{{ ingress_nginx_config.helm.repo_name }}"
    repo_url: "{{ ingress_nginx_config.helm.repo_url }}"
    repo_state: present

- name: Deploy the nginx ingress
  kubernetes.core.helm:
    chart_ref: "{{ ingress_nginx_config.helm.chart_ref }}"
    create_namespace: "{{ ingress_nginx_config.helm.create_namespace }}"
    release_name: "{{ ingress_nginx_config.helm.release_name }}"
    release_namespace: "{{ ingress_nginx_config.helm.release_namespace }}"
    release_state: present
    update_repo_cache: true
    release_values: "{{ ingress_nginx_config.helm.values | default(omit) }}"

- name: Get rid of traefik
  ansible.builtin.include_tasks: remove_traefik.yaml
