---
- name: Install ingress-nginx deployment
  ansible.builtin.include_tasks: install.yaml
  when: ingress_nginx_config.state == "present"
- name: Remove ingress-nginx deployment
  ansible.builtin.include_tasks: remove.yaml
  when: ingress_nginx_config.state == "absent"
