---
- name: Install ingress-nginx deployment
  ansible.builtin.include_tasks: install.yaml
  when: state == "present"
- name: Remove ingres--nginx deployment
  ansible.builtin.include_tasks: remove.yaml
  when: state == "absent"
