
certmanager_config_defaults: &config
  state: present
  version: v1.19.2
  acme:
    email: null
    server: https://acme-v02.api.letsencrypt.org/directory
    ingress_class: null
  helm:
    chart:
      ref: jetstack/cert-manager
      version: v1.19.2
      release_name: cert-manager
      release_namespace: cert-manager
      create_namespace: true
    repos:
      - name: jetstack
        url: https://charts.jetstack.io
    repo_key_dest: /usr/share/keyrings/helm_signing.asc
    values:
      crds:
        enabled: true
certmanager_config: *config
