---
- name: Install postgres deployment
  ansible.builtin.include_tasks: install.yaml
  when: postgres_config.state == "present"
- name: Remove postgres deployment
  ansible.builtin.include_tasks: remove.yaml
  when: postgres_config.state == "absent"
