---
argument_specs:
  # tasks/main.yml entry point
  main:
    short_description: Install OpenLDAP
    description:
      - Installs a OpenLDAP instance using helm
    author:
      - Jörn Krenzer
    options:
      state:
        type: str
        choices:
          - present
          - absent
        default: present
        required: true
        description: "Desired state of the role"
      version:
        type: str
        required: true
        default: "2.6"
        description: "Version of the app to install"
      helm:
        type: dict
        options:
          chart_ref:
            type: str
            required: true
            default: jkrenzer/openldap
            description: "Reference name of the helm chart"
          create_namespace:
            type: bool
            required: true
            default: true
            description: "Create the namespace if it does not exist"
          release_name:
            type: str
            required: true
            default: openldap
            description: "Name of the helm release"
          release_namespace:
            type: str
            required: true
            default: openldap
            description: "Namespace of the helm release"
          repo_name:
            type: str
            required: true
            default: jkrenzer
            description: "Name of the helm repository"
          repo_url:
            type: str
            required: true
            default: https://github.com/jkrenzer/helm-charts
            description: "Helm repository to use"
          repo_key_dest:
            type: str
            required: true
            default: /usr/share/keyrings/helm_signing.asc
            description: "Destination for the signing keys of helm"
          values:
            type: list
            elements: dict
            description: "Values to set in the helm chart"
