
# Namespaced defaults for ingress_nginx

ingress_nginx_config_defaults: &config
  state: present
  version: v1.5.3
  helm:
    chart:
      ref: ingress-nginx/ingress-nginx
      version: v1.5.3
      release_name: ingress-nginx
      release_namespace: ingress-nginx
      create_namespace: true
    repos:
      - name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx
    repo_key_dest: /usr/share/keyrings/helm_signing.asc
    values:
      controller:
        extraArgs:
          enable-ssl-passthrough: 1
ingress_nginx_config: *config
