---
dependencies:
  - role: helm
    vars:
      state: present
  - role: openldap
    vars:
      state: present
    when: "values.ldap.enabled"
galaxy_info:
  role_name: mailserver
  author: Jörn Krenzer
  description: Install and configure Docker-Mailserver
  license: "license (GPL3)"
  min_ansible_version: "2.10"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: AIX
      versions:
        - all
  galaxy_tags:
    - container
    - orchestration
    - kubernetes
    - helm
    - packages
