---
- name: Add the repo
  kubernetes.core.helm_repository:
    name: "{{ helm.repo_name }}"
    repo_url: "{{ helm.repo_url }}"
    repo_state: present

- name: Deploy chart
  kubernetes.core.helm:
    chart_ref: "{{ helm.chart_ref }}"
    create_namespace: "{{ helm.create_namespace }}"
    release_name: "{{ helm.release_name }}"
    release_namespace: "{{ helm.release_namespace }}"
    release_state: present
    update_repo_cache: true
    chart_version: "{{ version }}"
    release_values: "{{ helm.values }}"
