---
- name: Add the repo
  kubernetes.core.helm_repository:
    name: "{{ openldap_config.helm.repo_name }}"
    repo_url: "{{ openldap_config.helm.repo_url }}"
    repo_state: present

- name: Deploy chart
  kubernetes.core.helm:
    chart_ref: "{{ openldap_config.helm.chart_ref }}"
    create_namespace: "{{ openldap_config.helm.create_namespace }}"
    release_name: "{{ openldap_config.helm.release_name }}"
    release_namespace: "{{ openldap_config.helm.release_namespace }}"
    release_state: present
    update_repo_cache: true
    chart_version: "{{ openldap_config.version }}"
    release_values: "{{ openldap_config.helm.values | default(omit) }}"
