
# Namespaced defaults for openldap

openldap_config_defaults: &config
  state: present
  version: '2.6'
  helm:
    chart:
      ref: jkrenzer/openldap
      version: '2.6'
      release_name: openldap
      release_namespace: openldap
      create_namespace: true
    repos:
      - name: jkrenzer
        url: https://github.com/jkrenzer/helm-charts
    repo_key_dest: /usr/share/keyrings/helm_signing.asc
openldap_config: *config
