---
argument_specs:
  main:
    short_description: Argument spec for certmanager role
    options:
      certmanager_config_defaults:
        description: Default configuration for certmanager Helm chart
        type: dict
        options:
          state:
            type: str
            choices:
              - present
              - absent
            default: present
            description: Desired state of the role
          version:
            type: str
            default: v1.5.3
            description: Version of the app to install
          helm:
            type: dict
            options:
              chart_ref:
                type: str
                default: jetstack/cert-manager
                description: Reference name of the helm chart
              create_namespace:
                type: bool
                default: true
                description: Create the namespace if it does not exist
              release_name:
                type: str
                default: cert-manager
                description: Name of the helm release
              release_namespace:
                type: str
                default: cert-manager
                description: Namespace of the helm release
              repo_name:
                type: str
                default: jetstack
                description: Name of the helm repository
              repo_url:
                type: str
                default: https://charts.jetstack.io
                description: Helm repository to use
              repo_key_dest:
                type: str
                default: /usr/share/keyrings/helm_signing.asc
                description: Destination for the signing keys of helm
              values:
                type: dict
                description: Values to set in the helm chart
                default:
                  crds:
                    enabled: true
      certmanager_config:
        description: Configuration for certmanager Helm chart (overrides defaults)
        type: dict
        default: "{{ certmanager_config_defaults }}"
