
# Namespaced defaults for mailserver

mailserver_config_defaults: &config
  state: present
  version: v13.3.0
  helm:
    chart:
      ref: jkrenzer/mailserver
      version: v13.3.0
      release_name: mailserver
      release_namespace: database
      create_namespace: true
    repos:
      - name: jkrenzer
        url: https://github.com/jkrenzer/helm-charts
      # - name: docker-mailserver
      #   url: https://docker-mailserver.github.io/docker-mailserver-helm
    repo_key_dest: /usr/share/keyrings/helm_signing.asc
mailserver_config: *config
