---
- name: Add stakater repo
  kubernetes.core.helm_repository:
    name: "{{ reloader_config.helm.repo_name }}"
    repo_url: "{{ reloader_config.helm.repo_url }}"
    repo_state: present

- name: Deploy the reloader
  kubernetes.core.helm:
    chart_ref: "{{ reloader_config.helm.chart_ref }}"
    create_namespace: "{{ reloader_config.helm.create_namespace }}"
    release_name: "{{ reloader_config.helm.release_name }}"
    release_namespace: "{{ reloader_config.helm.release_namespace }}"
    release_state: present
    update_repo_cache: true
    set_values: "{{ reloader_config.helm.set_values | default(omit) }}"
    chart_version: "{{ reloader_config.version }}"
    release_values: "{{ reloader_config.helm.values | default(omit) }}"
