---
- name: Install Helm
  when: helm_config.state == "present"
  ansible.builtin.include_tasks: install.yaml
- name: Remove Helm
  when: helm_config.state == "absent"
  ansible.builtin.include_tasks: remove.yaml
