---
- name: Remove helm
  ansible.builtin.apt:
    name: helm
    state: absent
- name: Remove helm repository from sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by={{ helm_repo_key_dest }}] https://baltocdn.com/helm/stable/debian/ all main"
    state: absent
# Not sure yet how to remove these
#
# - name: Update repositories cache and install gpg
#   ansible.builtin.apt:
#     name: gpg
#     update_cache: true
# - name: Add Apt signing key for helm
#   ansible.builtin.get_url:
#     url: https://baltocdn.com/helm/signing.asc
#     dest: "{{  helm_repo_key_dest }}"
#     mode: "0600"
