---
- name: Install mailserver deployment
  ansible.builtin.include_tasks: install.yaml
  when: mailserver_config.state == "present"
- name: Remove mailserver deployment
  ansible.builtin.include_tasks: remove.yaml
  when: mailserver_config.state == "absent"
