---
argument_specs:
  # tasks/main.yml entry point
  main:
    short_description: Install helm
    description:
      - Installs helm
    author:
      - Jörn Krenzer
    options:
      helm_repo_key_dest:
        type: "str"
        required: true
        default: /usr/share/keyrings/helm_signing.asc
        description: "Destination for the signing keys of helm"
