---
- name: Install Certmanager
  hosts: k3s_cluster:&server
  environment:
    K8S_AUTH_API_KEY: "{{ token | quote }}"
    K8S_AUTH_KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  become: true
  roles:
    - jkrenzer.server_linux_kubernetes.certmanager
