- name: "Zot Registry | Uninstall operator"
  kubernetes.core.helm:
    name: "{{ name }}"
    release_namespace: "{{ namespace }}"
    state: absent
    wait: true
  ignore_errors: true
  vars:
    name: "{{ zot_registry_config.name }}"
    namespace: "{{ zot_registry_config.namespace }}"

- name: "Zot Registry | Delete namespace"
  when: kb_uninstall_delete_namespace
  kubernetes.core.k8s:
    state: absent
    kind: Namespace
    name: "{{ namespace }}"
  vars:
    namespace: "{{ zot_registry_config.namespace }}"