---
- name: Install cert-manager deployment
  ansible.builtin.include_tasks: install.yaml
  when: certmanager_config.state == "present"
- name: Remove cert-manager deployment
  ansible.builtin.include_tasks: remove.yaml
  when: certmanager_config.state == "absent"
