---
- name: Install cert-manager deployment
  ansible.builtin.include_tasks: install.yaml
  when: state == "present"
- name: Remove cert-manager deployment
  ansible.builtin.include_tasks: remove.yaml
  when: state == "absent"
