---
- name: Add jetstack helm repo for cert-manager
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"
- name: Deploy the cert-manager
  kubernetes.core.helm:
    chart_ref: "jetstack/cert-manager"
    create_namespace: true
    release_name: cert-manager
    release_namespace: cert-manager
    release_state: present
    set_values:
      - value: crds.enabled=true
