- name: Merge defaults into config
  ansible.builtin.set_fact:
    certmanager_config: >
      {{ certmanager_config_defaults | ansible.builtin.combine(certmanager_config, recursive=True, list_merge='replace') }}